"""define many-to-many relationship with Movie and Users

Revision ID: 857e985d3e53
Revises: d372fc15461b
Create Date: 2023-10-07 01:34:14.514369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857e985d3e53'
down_revision = 'd372fc15461b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_movies',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name=op.f('fk_user_movies_movie_id_movie')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_movies_user_id_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_movies')
    # ### end Alembic commands ###
