"""add movie_genre_association table

Revision ID: d7cae8c0a6cf
Revises: 857e985d3e53
Create Date: 2023-10-07 01:47:02.963800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7cae8c0a6cf'
down_revision = '857e985d3e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_genre_association',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name=op.f('fk_movie_genre_association_genre_id_genre')),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name=op.f('fk_movie_genre_association_movie_id_movie'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_genre_association')
    # ### end Alembic commands ###
